#!/usr/bin/env bash
echo "" > ~/.nanorc

echo "include \"~/.nano/apacheconf.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/arduino.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/asciidoc.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/asm.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/c.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/clojure.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/cmake.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/colortest.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/conf.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/csharp.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/css.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/cython.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/dot.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/dotenv.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/email.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/Dockerfile.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/fish.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/fortran.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/gentoo.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/git.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/gitcommit.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/glsl.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/go.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/groff.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/haml.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/haskell.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/ical.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/ini.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/inputrc.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/jade.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/java.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/javascript.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/js.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/json.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/keymap.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/kickstart.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/ledger.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/lisp.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/lua.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/makefile.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/man.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/markdown.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/mpdconf.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/mutt.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/nanorc.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/nginx.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/nmap.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/ocaml.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/patch.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/peg.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/perl.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/perl6.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/php.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/pkg-config.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/pkgbuild.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/po.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/pov.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/privoxy.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/puppet.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/pug.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/python.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/reST.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/rpmspec.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/ruby.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/rust.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/scala.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/sed.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/sh.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/sls.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/sql.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/svn.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/swift.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/systemd.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/tcl.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/tex.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/vala.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/verilog.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/vi.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/xml.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/xresources.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/yaml.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/yum.nanorc\"" >> ~/.nanorc
echo "include \"~/.nano/zsh.nanorc\"" >> ~/.nanorc

